apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus.server.fullname" . }}-server
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - kyma-system
  selector:
    matchLabels:
      app: prometheus-istio
      component: server
  endpoints:
  - path: /metrics
    targetPort: 9090
    honorLabels: true
    scheme: https
    tlsConfig: 
      caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
      certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
      keyFile: /etc/prometheus/secrets/istio.default/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod ceritifcate
  - params:
      'match[]':
      - '{__name__=~"workload:(.*)"}'
      - '{__name__=~"envoy(.*)"}'
    path: /federate
    targetPort: 9090
    honorLabels: true
    metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: 'workload:(.*)'
      targetLabel: "__name__"
      action: replace
    scheme: https
    tlsConfig: 
      caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
      certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
      keyFile: /etc/prometheus/secrets/istio.default/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod ceritifcate
