apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dex-service
spec:
  host: dex-service.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      caCertificates: /etc/prometheus/secrets/istio.default/root-cert.pem
      clientCertificate: /etc/prometheus/secrets/istio.default/cert-chain.pem
      privateKey: /etc/prometheus/secrets/istio.default/key.pem