{{if .Values.kcproxy.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kiali-server.name" . }}-secured # Denn brauchen wir ned
  labels:
      {{- include "kiali-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.kiali.spec.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: {{ template "kiali-server.name" . }}-kcproxy
{{end}}
